name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Ekstrak Project & Setup Env
      run: |
        sudo apt-get install -y unzip
        if [ -f MBG.zip ]; then
          unzip -o MBG.zip
        fi
        
        # Buat file .env dari .env.example jika ada
        if [ -f .env.example ]; then
          cp .env.example .env
        fi
        
        # Cek jika .env ada di subfolder
        find . -name ".env.example" -exec sh -c 'cp "$1" "${1%.example}"' _ {} \;

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew || true

    - name: Build with Gradle
      run: |
        if [ -f gradlew ]; then
          ./gradlew assembleDebug --stacktrace
        else
          gradle assembleDebug --stacktrace
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: '**/build/outputs/apk/debug/*.apk'
